# Generated by Django 3.2.5 on 2021-08-23 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('street', models.CharField(blank=True, max_length=400, verbose_name='Улица')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Штат')),
                ('zip_code', models.PositiveIntegerField(blank=True, default=0, verbose_name='Индекс')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')], verbose_name='Телефон')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo_image', models.ImageField(blank=True, default='pizzariaImages/pizzalogo.png', upload_to='pizzariaImages', verbose_name='Логотип')),
                ('email', models.EmailField(blank=True, max_length=245, verbose_name='Почта')),
                ('active', models.BooleanField(default=True, verbose_name='Актуальность')),
            ],
            options={
                'verbose_name': 'Пиццерия',
                'verbose_name_plural': 'Пиццерии',
            },
        ),
    ]
